import type { Achievement, Scene } from "@/types/story";

export const scenes: Scene[] = [
  {
    id: "opening",
    kind: "opening",
    eyebrow: "Пролог · Урал · 05:47",
    title: "Один большой\nпапин день",
    body: "Некоторые дороги начинаются ещё до того, как проснётся весь мир.",
    action: "Выйти на тропу",
    art: "/art/ural-dawn-trail-v2.png",
  },
  {
    id: "liza-trail",
    kind: "travel",
    eyebrow: "Глава первая · Лиза",
    title: "Там, где встаёт солнце",
    body: "На опушке уже ждут Лиза и Оскар.",
    action: "Подойти ближе",
    art: "/art/ural-dawn-trail-v2.png",
    traveller: "walker",
    travellerLabel: "Папа идёт по тропе к Лизе",
  },
  {
    id: "liza-meeting",
    kind: "meeting",
    eyebrow: "Вместе",
    title: "Рассвет умеет не торопиться",
    body: "Особенно когда рядом те, с кем можно просто молчать и смотреть, как начинается новый день.",
    action: "Сохранить этот момент",
    art: "/art/liza-sunrise-meeting-v5.jpg",
  },
  {
    id: "liza-message",
    kind: "message",
    eyebrow: "Лиза · для папы",
    title: "С днём рождения, папа!",
    body: "Спасибо, что рядом с тобой любая дорога кажется надёжной — даже если мы ещё не знаем, куда она приведёт.\n\nМне очень нравится твоя спокойная сила, любопытство к жизни и талант превращать обычный день в маленькое приключение.\n\nПусть впереди будет много маршрутов, на которых хватает времени и на большие цели, и на такие тихие рассветы вместе.",
    action: "Обнять Лизу",
    art: "/art/liza-sunrise-meeting-v5.jpg",
    author: "Лиза",
    portrait: "/people/liza-portrait-v1.jpg",
    sign: "Люблю, Лиза",
    notePlace: "Уральская тропа · 05:47",
    noteMark: "Рассвет",
  },
  {
    id: "liza-achievements",
    kind: "achievements",
    eyebrow: "Новые ачивки",
    title: "В папину коллекцию",
    body: "Лиза добавила две вещи, которые точно стоит взять с собой дальше.",
    action: "Продолжить путь",
    art: "/art/liza-sunrise-meeting-v5.jpg",
    author: "Лиза",
    achievementIds: ["steady-compass", "five-minutes"],
  },
  {
    id: "sonya-trail",
    kind: "travel",
    eyebrow: "Глава вторая · Соня",
    title: "По следу первого снега",
    body: "Лыжня ведёт через тихий лес к Соне и Альбусу.",
    action: "Догнать их",
    art: "/art/sonya-winter-trail-v2.png",
    traveller: "skier",
    travellerLabel: "Папа едет на лыжах к Соне и Альбусу",
  },
  {
    id: "sonya-meeting",
    kind: "meeting",
    eyebrow: "Вместе · Соня и Альбус",
    title: "Снег — это приглашение играть",
    body: "Особенно когда Альбус уже мчится навстречу, а серьёзный лыжный маршрут на минуту превращается в снежную возню.",
    action: "Запомнить этот смех",
    art: "/art/sonya-snow-meeting-v2.png",
  },
  {
    id: "sonya-message",
    kind: "message",
    eyebrow: "Соня · для папы",
    title: "Папа, с днём рождения! ❤️",
    body: "Мне кажется, тебе сложно желать стандартных «новых достижений», потому что ты и сам всегда находишь себе новые цели, идеи и вершины.\n\nЯ очень ценю в тебе эту способность не останавливаться, постоянно развиваться, пробовать новое и по-настоящему увлекаться тем, что делаешь.\n\nНо сегодня хочу пожелать тебе не только новых целей, а ещё больше времени просто жить в своё удовольствие — радоваться семье, близким, путешествиям, хорошим дням и всему тому, что уже есть.\n\nПусть тебе всегда будет интересно жить, хватает сил, свободы и любопытства на всё, что действительно хочется.\n\nЯ тобой горжусь и очень тебя люблю. С днём рождения, пап ❤️",
    action: "Обнять Соню",
    art: "/art/sonya-snow-meeting-v1.png",
    author: "Соня",
    portrait: "/people/sonya-portrait-v1.jpg",
    sign: "Люблю, Соня",
    notePlace: "Снежный лес · −12°",
    noteMark: "По лыжне",
  },
  {
    id: "sonya-achievements",
    kind: "achievements",
    eyebrow: "Новые ачивки",
    title: "Ещё две в коллекцию",
    body: "Соня вручает награды за папину надёжность и умение поддержать любую семейную авантюру.",
    action: "Продолжить путь",
    art: "/art/sonya-snow-meeting-v1.png",
    author: "Соня",
    achievementIds: ["winter-route", "walk-command"],
  },
  {
    id: "taya-trail",
    kind: "travel",
    eyebrow: "Глава третья · Тая",
    title: "Туда, где снег становится пеной",
    body: "За волнами уже виден берег — и Тая машет папе рукой.",
    action: "Доплыть до берега",
    art: "/art/taya-australia-trail-v2.png",
    traveller: "swimmer",
    travellerLabel: "Папа плывёт к Тае, которая машет ему с берега",
  },
  {
    id: "taya-meeting",
    kind: "meeting",
    eyebrow: "Вместе · Тая",
    title: "Иногда лучший план — смотреть в небо",
    body: "Волны остаются рядом, а спешить больше некуда: можно лежать на тёплом песке и угадывать фигуры в облаках.",
    action: "Оставить этот день в памяти",
    art: "/art/taya-beach-meeting-v1.png",
  },
  {
    id: "taya-message",
    kind: "message",
    eyebrow: "Тая · для папы",
    title: "С днём рождения, папа!",
    action: "Обнять Таю",
    art: "/art/taya-beach-meeting-v1.png",
    author: "Тая",
    portrait: "/people/taya-portrait-v1.jpg",
    sign: "Люблю, Тая",
    notePlace: "Австралийский берег · 12:20",
    noteMark: "С моря",
  },
  {
    id: "taya-achievements",
    kind: "achievements",
    eyebrow: "Новые ачивки",
    title: "Две награды с берега",
    body: "Тая добавляет в папину коллекцию спокойную силу и редкий талант вовремя отменить суету.",
    action: "Продолжить триатлон",
    art: "/art/taya-beach-meeting-v1.png",
    author: "Тая",
    achievementIds: ["calm-ocean", "cloud-watcher"],
  },
  {
    id: "fadey-trail",
    kind: "travel",
    eyebrow: "Глава четвёртая · Фадей",
    title: "Выше облаков",
    body: "Горная тропа ведёт к обзорной площадке, где Фадей уже ждёт папу рядом со своим велосипедом.",
    action: "Подняться к Фадею",
    art: "/art/fadey-krasnaya-polyana-trail-v4.png",
    traveller: "cyclist",
    travellerLabel: "Папа поднимается на велосипеде по горной тропе к Фадею",
  },
  {
    id: "fadey-meeting",
    kind: "meeting",
    eyebrow: "Вместе · Фадей",
    title: "С высоты всё становится понятнее",
    body: "Можно поставить велосипед рядом, перевести дыхание и просто смотреть, как горы уходят далеко за горизонт.",
    action: "Запомнить этот вид",
    art: "/art/fadey-mountain-meeting-v2.png",
  },
  {
    id: "fadey-message",
    kind: "message",
    eyebrow: "Фадей · для папы",
    title: "С днём рождения, папа!",
    action: "Обнять Фадея",
    art: "/art/fadey-mountain-meeting-v2.png",
    author: "Фадей",
    portrait: "/people/fadey-portrait-v1.jpg",
    sign: "Люблю, Фадей",
    notePlace: "Красная Поляна · 15:40",
    noteMark: "Высота",
  },
  {
    id: "fadey-achievements",
    kind: "achievements",
    eyebrow: "Новые ачивки",
    title: "Две награды с вершины",
    body: "Фадей вручает папе награды за силу, терпение и подозрительно короткие расстояния до любого финиша.",
    action: "Продолжить путь",
    art: "/art/fadey-mountain-meeting-v2.png",
    author: "Фадей",
    achievementIds: ["mountain-character", "one-more-climb"],
  },
  {
    id: "yarik-trail",
    kind: "travel",
    eyebrow: "Глава пятая · Ярик",
    title: "Последний рывок к закату",
    body: "Следы на песке ведут к финишу, где Ярик уже машет папе рукой.",
    action: "Добежать до Ярика",
    art: "/art/yarik-dubai-trail-v3.png",
    traveller: "runner",
    travellerLabel: "Папа бежит по дюнам к восьмилетнему Ярику",
  },
  {
    id: "yarik-meeting",
    kind: "meeting",
    eyebrow: "Вместе · Ярик",
    title: "У каждой дороги есть своя сказка",
    body: "После финиша папа открывает книгу, Ярик устраивается рядом, и пустыня на минуту становится самым уютным местом на свете.",
    action: "Дочитать до звёзд",
    art: "/art/yarik-desert-meeting-v3.png",
  },
  {
    id: "yarik-message",
    kind: "message",
    eyebrow: "Ярик · для папы",
    title: "С днём рождения, папа!",
    action: "Обнять Ярика",
    art: "/art/yarik-desert-meeting-v3.png",
    author: "Ярик",
    portrait: "/people/yarik-portrait-v1.jpg",
    sign: "Люблю, Ярик",
    notePlace: "Дюны · закат",
    noteMark: "Финиш",
  },
  {
    id: "yarik-achievements",
    kind: "achievements",
    eyebrow: "Новые ачивки",
    title: "Две награды у финиша",
    body: "Ярик добавляет в папину коллекцию умение идти до конца и особый талант превращать любое дело в соревнование.",
    action: "Зажечь фонарь",
    art: "/art/yarik-desert-meeting-v3.png",
    author: "Ярик",
    achievementIds: ["finish-together", "race-you-there"],
  },
  {
    id: "family-trail",
    kind: "travel",
    eyebrow: "Финальная глава · домой",
    title: "На свет в окнах",
    body: "Папа снова идёт пешком. Вечерняя тропа ведёт туда, где его ждут все.",
    action: "Войти в дом",
    art: "/art/final-evening-trail-v1.jpg",
    traveller: "walker",
    travellerLabel: "Папа с фонарём идёт по вечерней тропе к освещённому дому",
  },
  {
    id: "family-reunion",
    kind: "meeting",
    eyebrow: "Финал · все вместе",
    title: "Вот ты и дома",
    body: "За дверью — Лиза, Соня, Тая, Фадей и Ярик. Рядом Оскар и Альбус. Самый длинный маршрут дня заканчивается объятиями.",
    action: "Побыть вместе",
    art: "/art/family-fireplace-reunion-v1.jpg",
  },
  {
    id: "family-moment",
    kind: "meeting",
    eyebrow: "У камина · от всех детей",
    title: "С днём рождения, папа!",
    body: "Пусть впереди будет ещё много дорог. А куда бы они ни вели, знай: мы всегда рады встречать тебя вместе. Любим тебя!",
    action: "Открыть зал славы",
    art: "/art/family-fireplace-reunion-v1.jpg",
  },
  {
    id: "hall-of-fame",
    kind: "hall",
    eyebrow: "Финал · папина коллекция",
    title: "Зал славы",
    body: "Десять маленьких напоминаний о том, каким тебя видим мы. Нажми на любую ачивку, чтобы рассмотреть её.",
    action: "Пройти день ещё раз",
    art: "/art/family-fireplace-reunion-v1.jpg",
    achievementIds: ["steady-compass", "five-minutes", "winter-route", "walk-command", "calm-ocean", "cloud-watcher", "mountain-character", "one-more-climb", "finish-together", "race-you-there"],
  },
];

export const achievements: Achievement[] = [
  {
    id: "steady-compass",
    author: "Лиза",
    title: "Верный компас",
    description: "За умение находить спокойное и точное направление, когда остальные ещё сверяются с картой.",
    symbol: "✦",
  },
  {
    id: "five-minutes",
    author: "Лиза",
    title: "Ещё пять минут",
    description: "За семейный талант растянуть короткую остановку до отдельного маленького приключения.",
    symbol: "☀",
  },
  {
    id: "winter-route",
    author: "Соня",
    title: "Надёжный маршрут",
    description: "За спокойствие и опору, с которыми даже незнакомая лыжня кажется дорогой домой.",
    symbol: "❄",
  },
  {
    id: "walk-command",
    author: "Соня",
    title: "Главный по прогулкам",
    description: "За готовность поддержать слово «гулять», даже когда Альбус понимает его раньше всех остальных.",
    symbol: "♢",
  },
  {
    id: "calm-ocean",
    author: "Тая",
    title: "Спокойный океан",
    description: "За внутреннюю силу, рядом с которой большие волны становятся просто частью приключения.",
    symbol: "≈",
  },
  {
    id: "cloud-watcher",
    author: "Тая",
    title: "Главный по облакам",
    description: "За редкое умение вовремя отложить маршрут и найти в небе историю получше любого расписания.",
    symbol: "☁",
  },
  {
    id: "mountain-character",
    author: "Фадей",
    title: "Горный характер",
    description: "За силу и спокойствие, с которыми даже самый долгий подъём превращается в понятный маршрут.",
    symbol: "▲",
  },
  {
    id: "one-more-climb",
    author: "Фадей",
    title: "Ещё один подъём",
    description: "За фразу «осталось совсем чуть-чуть», после которой дорога почему-то успевает повернуть ещё три раза.",
    symbol: "↟",
  },
  {
    id: "finish-together",
    author: "Ярик",
    title: "Финишируем вместе",
    description: "За умение не просто дойти до цели, а сделать так, чтобы рядом тоже поверили в свои силы.",
    symbol: "◇",
  },
  {
    id: "race-you-there",
    author: "Ярик",
    title: "А кто быстрее?",
    description: "За волшебную фразу, после которой обычная дорога мгновенно превращается в самый важный забег дня.",
    symbol: "⚑",
  },
];
