import type { Achievement, Scene } from "@/types/story";

export const scenes: Scene[] = [
  {
    id: "opening",
    kind: "opening",
    eyebrow: "Пролог · Урал · 05:47",
    title: "Один большой\nпапин день",
    body: "Некоторые дороги начинаются ещё до того, как проснётся весь мир.",
    action: "Выйти на тропу",
    art: "/art/ural-dawn-trail-v2.png",
  },
  {
    id: "liza-trail",
    kind: "travel",
    eyebrow: "Глава первая · Лиза",
    title: "Там, где встаёт солнце",
    body: "На опушке уже ждут Лиза и Оскар.",
    action: "Подойти ближе",
    art: "/art/ural-dawn-trail-v2.png",
    traveller: "walker",
    travellerLabel: "Папа идёт по тропе к Лизе",
  },
  {
    id: "liza-meeting",
    kind: "meeting",
    eyebrow: "Вместе",
    title: "Рассвет умеет не торопиться",
    body: "Особенно когда рядом те, с кем можно просто молчать и смотреть, как начинается новый день.",
    action: "Сохранить этот момент",
    art: "/art/liza-sunrise-meeting-v5.jpg",
  },
  {
    id: "liza-message",
    kind: "message",
    eyebrow: "Лиза · для папы",
    title: "С днём рождения, папа!",
    body: "Спасибо, что рядом с тобой любая дорога кажется надёжной — даже если мы ещё не знаем, куда она приведёт.\n\nМне очень нравится твоя спокойная сила, любопытство к жизни и талант превращать обычный день в маленькое приключение.\n\nПусть впереди будет много маршрутов, на которых хватает времени и на большие цели, и на такие тихие рассветы вместе.",
    action: "Обнять Лизу",
    art: "/art/liza-sunrise-meeting-v5.jpg",
    author: "Лиза",
    portrait: "/people/liza-portrait-v1.jpg",
    sign: "Люблю, Лиза",
  },
  {
    id: "liza-achievements",
    kind: "achievements",
    eyebrow: "Новые ачивки",
    title: "В папину коллекцию",
    body: "Лиза добавила две вещи, которые точно стоит взять с собой дальше.",
    action: "Продолжить путь",
    art: "/art/liza-sunrise-meeting-v5.jpg",
    author: "Лиза",
    achievementIds: ["steady-compass", "five-minutes"],
  },
  {
    id: "liza-farewell",
    kind: "farewell",
    eyebrow: "Первая встреча пройдена",
    title: "Тропа становится зимней",
    body: "Лиза остаётся с Оскаром на опушке, а впереди трава уже серебрится и укрывается свежим снегом.",
    action: "Встретить зиму",
    art: "/art/liza-sunrise-meeting-v5.jpg",
  },
  {
    id: "sonya-trail",
    kind: "travel",
    eyebrow: "Глава вторая · Соня",
    title: "По следу первого снега",
    body: "Лыжня ведёт через тихий лес к Соне и Альбусу.",
    action: "Догнать их",
    art: "/art/sonya-winter-trail-v2.png",
    traveller: "skier",
    travellerLabel: "Папа едет на лыжах к Соне и Альбусу",
  },
  {
    id: "sonya-meeting",
    kind: "meeting",
    eyebrow: "Вместе · Соня и Альбус",
    title: "Снег — это приглашение играть",
    body: "Особенно когда Альбус уже мчится навстречу, а серьёзный лыжный маршрут на минуту превращается в снежную возню.",
    action: "Запомнить этот смех",
    art: "/art/sonya-snow-meeting-v2.png",
  },
  {
    id: "sonya-message",
    kind: "message",
    eyebrow: "Соня · для папы",
    title: "С днём рождения, папа!",
    body: "Спасибо, что ты всегда умеешь быть рядом — спокойно, надёжно и именно тогда, когда это особенно нужно.\n\nС тобой легко не бояться длинных дорог и новых поворотов. Ты напоминаешь, что любую серьёзную цель можно пройти с улыбкой, любопытством и заботой о тех, кто рядом.\n\nПусть впереди будет ещё много ясных утр, любимых маршрутов и счастливых остановок всей семьёй.",
    action: "Обнять Соню",
    art: "/art/sonya-snow-meeting-v1.png",
    author: "Соня",
    portrait: "/people/sonya-portrait-v1.jpg",
    sign: "Люблю, Соня",
  },
  {
    id: "sonya-achievements",
    kind: "achievements",
    eyebrow: "Новые ачивки",
    title: "Ещё две в коллекцию",
    body: "Соня вручает награды за папину надёжность и умение поддержать любую семейную авантюру.",
    action: "Продолжить путь",
    art: "/art/sonya-snow-meeting-v1.png",
    author: "Соня",
    achievementIds: ["winter-route", "walk-command"],
  },
  {
    id: "sonya-farewell",
    kind: "farewell",
    eyebrow: "Вторая встреча пройдена",
    title: "Снег становится морской пеной",
    body: "Папа обнимает Соню, гладит Альбуса и снова выходит на маршрут. Снежная пыль поднимается всё выше — впереди уже слышен океан.",
    action: "Пройти две встречи ещё раз",
    art: "/art/sonya-snow-meeting-v1.png",
  },
];

export const achievements: Achievement[] = [
  {
    id: "steady-compass",
    author: "Лиза",
    title: "Верный компас",
    description: "За умение находить спокойное и точное направление, когда остальные ещё сверяются с картой.",
    symbol: "✦",
  },
  {
    id: "five-minutes",
    author: "Лиза",
    title: "Ещё пять минут",
    description: "За семейный талант растянуть короткую остановку до отдельного маленького приключения.",
    symbol: "☀",
  },
  {
    id: "winter-route",
    author: "Соня",
    title: "Надёжный маршрут",
    description: "За спокойствие и опору, с которыми даже незнакомая лыжня кажется дорогой домой.",
    symbol: "❄",
  },
  {
    id: "walk-command",
    author: "Соня",
    title: "Главный по прогулкам",
    description: "За готовность поддержать слово «гулять», даже когда Альбус понимает его раньше всех остальных.",
    symbol: "♢",
  },
];
